root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
full_bin = "APP_ENV=development ./tmp/main"
log = "air_errors.log"
include_dir = []
exclude_dir = ["tmp"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_ext = ["log"]
kill_delay = "0s"
stop_on_error = true

[run]
cmds = []
pre_cmd = []
post_cmd = []
args = []
