FROM golang:1.24
WORKDIR /usr/local/app

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080
RUN curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

CMD ["air", "run", "main.go"]
